import { TerminalAnimation } from './TerminalAnimation'
import s from './Projects.module.css'

export function Projects() {
  return (
    <section className={s.section} id="work">
      <div className="wrap">
        <div className="section-eyebrow">selected work · 2026</div>

        <article className={s.featured}>
          <div className={s.pfContent}>
            <div className={s.pfMeta}>
              <span className={s.badge}>★ featured</span>
              <span>open source · npm</span>
              <span>·</span>
              <span>v0.1</span>
            </div>
            <h2 className={s.pfTitle}>pw<span className={s.slash}>/</span>forge</h2>
            <div className={s.pfTag}>A CLI that scaffolds a real Playwright TypeScript project from a single URL.</div>
            <p className={s.pfDesc}>
              Template-first generator with an optional Claude-powered enhancement pass.
              No API key required to work — POMs, fixtures, config, CI, README, all sensible defaults.
            </p>
            <ul className={s.pfBullets}>
              <li>Generates a full POM-structured suite in one command</li>
              <li>Optional <span className="kbd">--ai</span> flag for site-aware test scenarios</li>
              <li>Published to npm · zero-config CI workflow included</li>
            </ul>
            <div className={s.pfCta}>
              <a href="https://github.com/dudiadikaryaa" target="_blank" rel="noopener" className="btn primary">View repo →</a>
              <a href="#" className="btn">npx pwforge ↗</a>
            </div>
          </div>
          <TerminalAnimation />
        </article>

        <div className={s.demoGrid}>
          <article className={s.demoCard}>
            <div className={s.corner} />
            <div className={s.cardMeta}><span className={s.num}>02</span><span>example output</span></div>
            <h3 className={s.cardTitle}>pwforge-demo<br /><span className={s.cardTitleIt}>/saucedemo</span></h3>
            <p className={s.copy}>Generated by pwforge, then hand-enhanced. Full E2E flow on the QA community&apos;s standard demo storefront — login, listing, cart, checkout.</p>
            <div className={s.chips}>
              <span>login</span><span>cart</span><span>checkout</span><span>POM</span><span>CI</span>
            </div>
            <a href="https://github.com/dudiadikaryaa" target="_blank" rel="noopener" className={s.cardLink}>Open repo <span>→</span></a>
          </article>
          <article className={s.demoCard}>
            <div className={s.corner} />
            <div className={s.cardMeta}><span className={s.num}>03</span><span>example output</span></div>
            <h3 className={s.cardTitle}>pwforge-demo<br /><span className={s.cardTitleIt}>/demoqa</span></h3>
            <p className={s.copy}>A second example on a UI-rich practice site. Different POM shape, different patterns — modals, drag-and-drop, complex form interactions.</p>
            <div className={s.chips}>
              <span>forms</span><span>modals</span><span>drag-drop</span><span>alerts</span><span>CI</span>
            </div>
            <a href="https://github.com/dudiadikaryaa" target="_blank" rel="noopener" className={s.cardLink}>Open repo <span>→</span></a>
          </article>
        </div>
      </div>
    </section>
  )
}
